[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  baseUrl = "https://mobile.peoplestech.com"
  buildDir = "output"
  prettyURLs = true
  trailingSlash = true
  exclude = [
    "**/404.html",
    "**/404/**",
    "**/500.html",
    "**/500/**",
    "**/admin/**"
  ]