backend:
  name: git-gateway
  branch: main

local_backend: true # Allow local DecapCMS

publish_mode: editorial_workflow
media_folder: "src/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "clusters" # Collections is a reserved word
    label: "Collections"
    folder: "src/_clusters"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "cluster" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Intro", name: "intro", widget: "markdown" }
      - label: "Hero Image"
        name: "hero"
        widget: "image"
        required: false

  - name: "journals"
    label: "Journal"
    folder: "src/_journals"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "entry" }
      - { label: "Headline", name: "title", widget: "string" }
      - label: "Highlight"
        name: "highlight"
        widget: "string"
        pattern: ['.*{0,85}', "Must be 85 characters or less"]
      - label: "Location"
        name: "location"
        widget: string
        hint: "Enter either [City] or [City, Country]"
      - label: "Collection"
        name: "clusters"
        widget: "relation"
        collection: "clusters"
        search_fields: [ "title" ]
        value_field: "title"
        required: true
      - label: "Related Events"
        name: "related_events"
        widget: "relation"
        collection: "events"
        search_fields: [ "title" ]
        value_field: "title" # should this be an ID?
        multiple: true
        required: false
      - label: "Tags"
        name: "tags"
        widget: "relation"
        collection: "tags"
        search_fields: [ "name" ]
        value_field: "name"
        multiple: true
        min: 1
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
        required: false
      - label: "Source"
        name: "source"
        widget: "string"
        required: false
      - label: "Source Link"
        name: "source_link"
        widget: "string"
        required: false
        pattern: ['https?\:\/\/.*\.[a-zA-Z0-9]{2,}', "Must be a valid URL"]
      - label: "Media Credit"
        name: "media_credit"
        widget: "string"
        required: false
      - label: "Media Link"
        name: "media_link"
        widget: "string"
        required: false
        pattern: ['https?\:\/\/.*\.[a-zA-Z0-9]{2,}', "Must be a valid URL"]
      - { label: "Alt Text", name: "media_alt", widget: "string", required: false }
      - { label: "Outbound links", name: "outbound_links", widget: "markdown", required: false }

  - name: "events" # Used in routes, e.g., /admin/collections/events
    label: "Events" # Used in the UI
    folder: "src/_events" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}" # Filename template, e.g., title-YYYY-MM-DD.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "entry" }
      - { label: "Headline", name: "title", widget: "string" }
      - label: "Location"
        name: "location"
        widget: string
        hint: "Enter either [City] or [City, Country]"
      - label: "Collection"
        name: "clusters"
        widget: "relation"
        collection: "clusters"
        search_fields: [ "title" ]
        value_field: "title"
        required: true
      - label: "Tags"
        name: "tags"
        widget: "relation"
        collection: "tags"
        search_fields: [ "name" ]
        value_field: "name"
        multiple: true
        min: 1
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
        required: false
      - label: "Source"
        name: "source"
        widget: "string"
        required: false
      - label: "Source Link"
        name: "source_link"
        widget: "string"
        required: false
        pattern: ['https?\:\/\/.*\.[a-zA-Z0-9]{2,}', "Must be a valid URL"]
      - label: "Media Credit"
        name: "media_credit"
        widget: "string"
        required: false
      - label: "Media Link"
        name: "media_link"
        widget: "string"
        required: false
        pattern: ['https?\:\/\/.*\.[a-zA-Z0-9]{2,}', "Must be a valid URL"]
      - { label: "Outbound links", name: "outbound_links", widget: "markdown", required: false }

  - name: "prompts"
    label: "Prompts"
    slug: "{{question}}"
    folder: "src/_prompts"
    create: true
    fields:
      - label: "Collection"
        name: "clusters"
        widget: "relation"
        collection: "clusters"
        search_fields: [ "title" ]
        value_field: "title"
        required: true
      - { label: "Question", name: "question", widget: "string" }

  - name: "tags"
    label: "Tags"
    slug: "{{name}}"
    folder: "src/_tags"
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - label: "Type"
        name: "tag_type"
        widget: "select"
        options: ["collection", "decade"]
        required: true