backend:
  name: git-gateway
  branch: main

local_backend: true # Allow local DecapCMS

publish_mode: editorial_workflow
media_folder: "src/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "clusters" # Collections is a reserved word
    label: "Collections"
    folder: "src/_clusters"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "cluster" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Feature", name: "feature", hint: "Featured Collections appear on the homepage", widget: "boolean"}
      - label: "Highlight"
        name: "highlight"
        widget: "string"
        hint: 85 characters max
        pattern: ['.*{0,85}', "Must be 85 characters or less"]
        required: true
      - label: "Carousel Description"
        name: "carousel_description"
        widget: "string"
        hint: 110 characters max
        pattern: ['.*{0,110}', "Must be 110 characters or less"]
        required: true
      - label: "Intro"
        name: "intro"
        widget: "markdown"
        required: true
      - label: "Hero Image"
        name: "hero"
        widget: "image"
        required: false

  - name: "events" # Used in routes, e.g., /admin/collections/events
    label: "Events" # Used in the UI
    folder: "src/_events" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}" # Filename template, e.g., title-YYYY-MM-DD.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "entry" }
      - { label: "Headline", name: "title", widget: "string" }
      - label: "Location"
        name: "location"
        widget: string
        hint: "Enter either [City] or [City, Country]"
      - label: "Start Date"
        name: "start_date"
        widget: "object"
        fields:
          - label: "Year"
            name: "year"
            widget: "number"
            value_type: int
            min: 1940
            max: 2024
            required: true
          - label: "Month"
            name: "month"
            widget: "select"
            required: false
            options:
              - { label: "January", value: 1 }
              - { label: "February", value: 2 }
              - { label: "March", value: 3 }
              - { label: "April", value: 4 }
              - { label: "May", value: 5 }
              - { label: "June", value: 6 }
              - { label: "July", value: 7 }
              - { label: "August", value: 8 }
              - { label: "September", value: 9 }
              - { label: "October", value: 10 }
              - { label: "November", value: 11 }
              - { label: "December", value: 12 }
          - label: "Day"
            name: "day"
            widget: "number"
            value_type: int
            min: 1
            max: 31
            required: false
      - label: "End Date"
        name: "end_date"
        widget: "object"
        collapsed: true
        fields:
          - label: "Year"
            name: "year"
            widget: "number"
            value_type: int
            min: 1940
            max: 2024
            required: false
          - label: "Month"
            name: "month"
            widget: "select"
            required: false
            options:
              - { label: "January", value: 1 }
              - { label: "February", value: 2 }
              - { label: "March", value: 3 }
              - { label: "April", value: 4 }
              - { label: "May", value: 5 }
              - { label: "June", value: 6 }
              - { label: "July", value: 7 }
              - { label: "August", value: 8 }
              - { label: "September", value: 9 }
              - { label: "October", value: 10 }
              - { label: "November", value: 11 }
              - { label: "December", value: 12 }
          - label: "Day"
            name: "day"
            widget: "number"
            value_type: int
            min: 1
            max: 31
            required: false
      - label: "Collection"
        name: "clusters"
        widget: "relation"
        collection: "clusters"
        search_fields: [ "title" ]
        value_field: "title"
        required: true
      - label: "Tags"
        name: "tags"
        widget: "relation"
        collection: "tags"
        search_fields: [ "name" ]
        value_field: "name"
        multiple: true
        min: 1
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Media"
        name: "media"
        widget: "object"
        fields:
          - label: "Image"
            name: "thumbnail"
            widget: "image"
            required: false
          - label: "Alt Text"
            name: "alt"
            widget: "string"
            required: true
          - label: "Credit"
            name: "credit"
            widget: "string"
            required: false
          - label: "Link"
            name: "link"
            widget: "string"
            required: false
            pattern: ['https?\:\/\/.*\.[a-zA-Z0-9]{2,}', "Must be a valid URL"]
      - label: "Source"
        name: "source"
        widget: "string"
        required: false
      - label: "Source Link"
        name: "source_link"
        widget: "string"
        required: false
        pattern: ['https?\:\/\/.*\.[a-zA-Z0-9]{2,}', "Must be a valid URL"]
      - { label: "Outbound links", name: "outbound_links", widget: "markdown", required: false }

  - name: "ctas"                       # Used in routes, e.g., /admin/collections/events
    label: "CTAs"                      # Used in the UI
    label_singular: "Call To Action"   # Used in the UI
    folder: "src/_ctas"                # The path to the folder where the documents are stored
    create: true                       # Allow users to create new documents in this collection
    slug: "{{title}}"                  # Filename template, e.g., title-YYYY-MM-DD.md
    fields:                            # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "cta" }
      - { label: "Headline", name: "title", widget: "string" }
      - label: "Collection"
        name: "clusters"
        widget: "relation"
        collection: "clusters"
        search_fields: [ "title" ]
        value_field: "title"
        required: true
      - label: "Tags"
        name: "tags"
        widget: "relation"
        collection: "tags"
        search_fields: [ "name" ]
        value_field: "name"
        multiple: true
        min: 1
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Media"
        name: "media"
        widget: "object"
        fields:
          - label: "Image"
            name: "thumbnail"
            widget: "image"
            required: false
          - label: "Alt Text"
            name: "alt"
            widget: "string"
            required: true
          - label: "Credit"
            name: "credit"
            widget: "string"
            required: false
          - label: "Link"
            name: "link"
            widget: "string"
            required: false
            pattern: ['https?\:\/\/.*\.[a-zA-Z0-9]{2,}', "Must be a valid URL"]
      - label: "Source"
        name: "source"
        widget: "string"
        required: false
      - label: "Source Link"
        name: "source_link"
        widget: "string"
        required: false
        pattern: ['https?\:\/\/.*\.[a-zA-Z0-9]{2,}', "Must be a valid URL"]
      - { label: "Outbound links", name: "outbound_links", widget: "markdown", required: false }

  - name: "journals"
    label: "Journal"
    folder: "src/_journals"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "entry" }
      - { label: "Headline", name: "title", widget: "string" }
      - label: "Highlight"
        name: "highlight"
        widget: "string"
        pattern: ['.*{0,85}', "Must be 85 characters or less"]
      - label: "Location"
        name: "location"
        widget: string
        hint: "Enter either [City] or [City, Country]"
      - label: "Collection"
        name: "clusters"
        widget: "relation"
        collection: "clusters"
        search_fields: [ "title" ]
        value_field: "title"
        required: true
      - label: "Related Events"
        name: "related_events"
        widget: "relation"
        collection: "events"
        search_fields: [ "title" ]
        value_field: "title" # should this be an ID?
        multiple: true
        required: false
      - label: "Tags"
        name: "tags"
        widget: "relation"
        collection: "tags"
        search_fields: [ "name" ]
        value_field: "name"
        multiple: true
        min: 1
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Media"
        name: "media"
        widget: "object"
        fields:
          - label: "Image"
            name: "thumbnail"
            widget: "image"
            required: false
          - label: "Alt Text"
            name: "alt"
            widget: "string"
            required: true
          - label: "Credit"
            name: "credit"
            widget: "string"
            required: false
          - label: "Link"
            name: "link"
            widget: "string"
            required: false
            pattern: ['https?\:\/\/.*\.[a-zA-Z0-9]{2,}', "Must be a valid URL"]
      - label: "Source"
        name: "source"
        widget: "string"
        required: false
      - label: "Source Link"
        name: "source_link"
        widget: "string"
        required: false
        pattern: ['https?\:\/\/.*\.[a-zA-Z0-9]{2,}', "Must be a valid URL"]
      - { label: "Outbound links", name: "outbound_links", widget: "markdown", required: false }

  - name: "pages"                          # Used in routes, e.g., /admin/collections/events
    label: "Pages"                         # Used in the UI
    label_singular: "General Content Page" # Used in the UI
    folder: "src/_pages"                   # The path to the folder where the documents are stored
    create: true                           # Allow users to create new documents in this collection
    identifier_field: "nav_label"          # Filename template, e.g., title-YYYY-MM-DD.md
    fields:                                # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "page" }
      - { label: "Permalink", name: "permalink", widget: "hidden", default: "/:slug.*" }
      - label: "Should the footer contain a link to this page?"
        name: "in_footer"
        widget: "boolean"
      - label: "Should the main navigation contain a link to this page?"
        name: "in_nav"
        widget: "boolean"
      - { label: "Headline", name: "title", widget: "string" }
      - label: "Navigation Label"
        name: "nav_label"
        widget: "string"
        hint: "The for the page link within the site navigation"
      - label: "Page URL location"
        name: "slug"
        widget: "string"
        hint: "ex:'about', will make this page avaiable at '/about'"
      - label: "Media"
        name: "media"
        widget: "object"
        fields:
          - label: "Image"
            name: "thumbnail"
            widget: "image"
            required: false
          - label: "Alt Text"
            name: "alt"
            widget: "string"
            required: true
          - label: "Credit"
            name: "credit"
            widget: "string"
            required: false
          - label: "Link"
            name: "link"
            widget: "string"
            required: false
            pattern: ['https?\:\/\/.*\.[a-zA-Z0-9]{2,}', "Must be a valid URL"]
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "prompts"
    label: "Prompts"
    slug: "{{question}}"
    folder: "src/_prompts"
    create: true
    fields:
      - label: "Collection"
        name: "clusters"
        widget: "relation"
        collection: "clusters"
        search_fields: [ "title" ]
        value_field: "title"
        required: true
      - { label: "Question", name: "question", widget: "string" }

  - name: "tags"
    label: "Tags"
    slug: "{{name}}"
    folder: "src/_tags"
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - label: "Type"
        name: "tag_type"
        widget: "select"
        options: ["collection", "decade"]
        required: true
